### ISSUE TITLE
ModuleNotFoundError No module named 'common'

### ISSUE THREAD

**Issue by eblin** [tolomea/django-beanstalk-worker#1]
Hi @tolomea 

it seems that there are missing files that didn't make it to the repo.

https://github.com/tolomea/django-beanstalk-worker/blob/b346b02905f7bf69e8ce961efff4f1157be826da/beanstalk_worker/services.py#L12

Great work on the package 👍

**Comment by tolomea** [comment]
dammit, that's my reward for testing in the same project it was developed in, I will chase this up in the morning, for now I think I've fixed it on master

**Comment by eblin** [comment]
> dammit, that's my reward for testing in the same project it was developed in, I will chase this up in the morning, for now I think I've fixed it on master

Haha no worries, thank you for the quick fix!  I wasn't sure if D2 was something special you had but I see is just plain decimal.Decimal

However I think you missed `import decimal` at the top :)

or `from decimal import Decimal` would probably be better

edit: ignore this, I just saw it on the top, that's what I get from just looking at the diff! 🤦‍♂️

**Comment by tolomea** [comment]
the import was already there

**Comment by tolomea** [comment]
D2 was actually short for decimal with two decimal places, because that code base only uses decimals for money.
```
def D2(f):
    return Decimal(f).quantize(Decimal(".01"), ROUND_HALF_UP)
```

**Comment by tolomea** [comment]
I've released that on pypi

**Comment by avivra** [comment]
Hi, it seems like the version on pip is still the one with this error.

**Comment by tolomea** [comment]
Sorry about that. Not sure what happened there but the correct version is now on pip.
